package models

import (
	"time"

	"github.com/google/uuid"
	"gorm.io/gorm"
)

// User represents the person registered via Google SSO
type User struct {
	// Primary Key using UUID v4 (Auto-generated by Supabase/Postgres)
	ID       uuid.UUID `gorm:"type:uuid;default:gen_random_uuid();primaryKey" json:"id"`
	GoogleID string    `gorm:"uniqueIndex;not null" json:"google_id"`
	Email    string    `gorm:"uniqueIndex;not null" json:"email"` // Used for matching bank emails
	Name     string    `gorm:"not null" json:"name"`
	Picture  string    `json:"picture"`

	// Standard GORM timestamps
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt time.Time      `json:"updated_at"`
	DeletedAt gorm.DeletedAt `gorm:"index" json:"-"`

	// Relationships: 1 User has many Transactions
	// CASCADE: Deleting a user will automatically remove all their transaction history
	Transactions []Transaction `gorm:"foreignKey:UserID;constraint:OnUpdate:CASCADE,OnDelete:CASCADE;" json:"-"`
}