package recurring

import (
	"context"
	"errors"
	"fmt"
	"time"

	"walletx-be/internal/modules/transaction"
	"walletx-be/internal/platform/cache"
	"walletx-be/internal/platform/logger"

	"github.com/google/uuid"
)

var validFrequencies = map[string]bool{"weekly": true, "monthly": true, "yearly": true}

// TransactionCreator is the narrow capability the recurring processor needs to
// emit generated transactions.
type TransactionCreator interface {
	Create(ctx context.Context, txn *transaction.Transaction) error
}

// Service encapsulate recurring business logic.
type Service interface {
	Create(ctx context.Context, userID uuid.UUID, input CreateInput) (*Config, error)
	List(ctx context.Context, userID uuid.UUID) ([]Config, error)
	GetByID(ctx context.Context, id, userID uuid.UUID) (*Config, error)
	Update(ctx context.Context, id, userID uuid.UUID, input UpdateInput) (*Config, error)
	Delete(ctx context.Context, id, userID uuid.UUID) error
	ProcessDue(ctx context.Context) error
}

type service struct {
	repo         Repository
	txCreator    TransactionCreator
	cacheManager cache.DashboardCacheManager
	logger       logger.Logger
}

func NewService(repo Repository, txCreator TransactionCreator, cacheManager cache.DashboardCacheManager, logger logger.Logger) Service {
	return &service{
		repo:         repo,
		txCreator:    txCreator,
		cacheManager: cacheManager,
		logger:       logger,
	}
}

func (s *service) Create(ctx context.Context, userID uuid.UUID, input CreateInput) (*Config, error) {
	if !validFrequencies[input.Frequency] {
		return nil, fmt.Errorf("invalid frequency '%s': must be 'weekly', 'monthly', or 'yearly'", input.Frequency)
	}
	if input.Amount <= 0 {
		return nil, errors.New("amount must be greater than 0")
	}

	config := &Config{
		UserID:      userID,
		CategoryID:  input.CategoryID,
		Amount:      input.Amount,
		Frequency:   input.Frequency,
		StartDate:   input.StartDate,
		NextDueDate: input.StartDate,
	}

	if err := s.repo.Create(ctx, config); err != nil {
		return nil, err
	}
	return config, nil
}

func (s *service) List(ctx context.Context, userID uuid.UUID) ([]Config, error) {
	return s.repo.List(ctx, userID)
}

func (s *service) GetByID(ctx context.Context, id, userID uuid.UUID) (*Config, error) {
	return s.repo.GetByID(ctx, id, userID)
}

func (s *service) Update(ctx context.Context, id, userID uuid.UUID, input UpdateInput) (*Config, error) {
	if !validFrequencies[input.Frequency] {
		return nil, fmt.Errorf("invalid frequency '%s': must be 'weekly', 'monthly', or 'yearly'", input.Frequency)
	}
	if input.Amount <= 0 {
		return nil, errors.New("amount must be greater than 0")
	}

	config, err := s.repo.GetByID(ctx, id, userID)
	if err != nil {
		return nil, err
	}

	config.Amount = input.Amount
	config.Frequency = input.Frequency
	if !input.StartDate.IsZero() {
		config.StartDate = input.StartDate
	}

	if err := s.repo.Update(ctx, config); err != nil {
		return nil, err
	}
	return config, nil
}

func (s *service) Delete(ctx context.Context, id, userID uuid.UUID) error {
	return s.repo.Delete(ctx, id, userID)
}

func (s *service) ProcessDue(ctx context.Context) error {
	configs, err := s.repo.GetDueConfigs(ctx)
	if err != nil {
		return err
	}

	if len(configs) == 0 {
		return nil
	}

	affectedUsers := make(map[uuid.UUID]bool)

	for _, config := range configs {
		catID := config.CategoryID
		txn := &transaction.Transaction{
			UserID:          config.UserID,
			CategoryID:      &catID,
			Amount:          config.Amount,
			Merchant:        "Recurring Transaction",
			Note:            "Auto-generated by recurring schedule",
			TransactionDate: config.NextDueDate,
			MessageID:       nil,
			IsRecurring:     true,
		}

		if err := s.txCreator.Create(ctx, txn); err != nil {
			continue
		}

		affectedUsers[config.UserID] = true

		config.NextDueDate = s.advanceDate(config.NextDueDate, config.Frequency)
		_ = s.repo.Update(ctx, &config)
	}

	for userID := range affectedUsers {
		s.invalidateDashboardCache(ctx, userID)
	}

	return nil
}

func (s *service) invalidateDashboardCache(ctx context.Context, userID uuid.UUID) {
	if err := s.cacheManager.InvalidateUserCache(ctx, userID.String()); err != nil {
		s.logger.WithError(err).Warn("Failed to invalidate dashboard cache")
	}
}

func (s *service) advanceDate(t time.Time, frequency string) time.Time {
	switch frequency {
	case "weekly":
		return t.AddDate(0, 0, 7)
	case "yearly":
		return t.AddDate(1, 0, 0)
	default:
		return t.AddDate(0, 1, 0)
	}
}
