package models

import (
	"time"

	"github.com/google/uuid"
	"gorm.io/gorm"
)

// Transaction represents a financial record — either extracted from a bank email
// by the IMAP worker, created manually by the user, or generated by the recurring worker.
type Transaction struct {
	ID uuid.UUID `gorm:"type:uuid;default:gen_random_uuid();primaryKey" json:"id"`

	// Belongs to User
	UserID uuid.UUID `gorm:"type:uuid;not null;index" json:"user_id"`

	// Optional FK to categories (nil for uncategorised transactions)
	CategoryID *uuid.UUID `gorm:"type:uuid;index" json:"category_id"`

	// Numeric type used for high precision currency (15 total digits, 2 decimal places)
	Amount          float64   `gorm:"type:numeric(15,2);not null" json:"amount"`
	Merchant        string    `gorm:"not null"                    json:"merchant"`
	Note            string    `gorm:"default:''"                  json:"note"`
	TransactionDate time.Time `gorm:"not null"                    json:"transaction_date"`

	// IDEMPOTENCY KEY: Unique Email Message-ID — nullable for manually-created transactions
	// The DB column allows NULL; unique constraint applied at DB level (unique + nullable).
	MessageID *string `gorm:"uniqueIndex" json:"message_id,omitempty"`

	// True when this transaction was created by the recurring worker
	IsRecurring bool `gorm:"default:false" json:"is_recurring"`

	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt time.Time      `json:"updated_at"`
	DeletedAt gorm.DeletedAt `gorm:"index" json:"deleted_at"`

	// Associations
	User     User      `gorm:"foreignKey:UserID"     json:"-"`
	Category *Category `gorm:"foreignKey:CategoryID" json:"category,omitempty"`
}
