package transaction

import (
	"time"

	"walletx-be/internal/modules/auth"
	"walletx-be/internal/modules/category"

	"github.com/google/uuid"
)

// Transaction represents a financial record — either extracted from a bank email
// by the IMAP worker, created manually by the user, or generated by the recurring worker.
type Transaction struct {
	ID uuid.UUID `json:"id"`

	// Belongs to User
	UserID uuid.UUID `json:"user_id"`

	// Optional FK to categories (nil for uncategorised transactions)
	CategoryID *uuid.UUID `json:"category_id"`

	// Numeric type used for high precision currency (15 total digits, 2 decimal places)
	Amount          float64   `json:"amount"`
	Merchant        string    `json:"merchant"`
	Note            string    `json:"note"`
	TransactionDate time.Time `json:"transaction_date"`

	// IDEMPOTENCY KEY: Unique Email Message-ID — nullable for manually-created transactions
	// The DB column allows NULL; unique constraint applied at DB level (unique + nullable).
	MessageID *string `json:"message_id,omitempty"`

	// True when this transaction was created by the recurring worker
	IsRecurring bool `json:"is_recurring"`

	CreatedAt time.Time  `json:"created_at"`
	UpdatedAt time.Time  `json:"updated_at"`
	DeletedAt *time.Time `json:"deleted_at"`

	// Associations
	User     auth.User          `json:"-"`
	Category *category.Category `json:"category,omitempty"`
}

// CategoryExpense is the result of a category-expense aggregation used by the
// `/reports/expenses` endpoint.
type CategoryExpense struct {
	CategoryName string  `json:"category_name"`
	TotalAmount  float64 `json:"total_amount"`
	Percentage   float64 `json:"percentage"`
}
