package workers

import (
	"time"

	"walletx-be/pkg/models"
	"walletx-be/pkg/repository"

	"github.com/google/uuid"
	"github.com/sirupsen/logrus"
)

// RecurringWorker processes due recurring transaction configs on a schedule
type RecurringWorker struct {
	recurringRepo   repository.RecurringRepository
	transactionRepo repository.TransactionRepository
}

// NewRecurringWorker creates a new RecurringWorker instance
func NewRecurringWorker(recurringRepo repository.RecurringRepository, transactionRepo repository.TransactionRepository) *RecurringWorker {
	return &RecurringWorker{
		recurringRepo:   recurringRepo,
		transactionRepo: transactionRepo,
	}
}

// ProcessDueRecurring is the core cron job function.
// It finds all recurring configs where next_due_date <= NOW(), inserts a new
// Transaction for each, then advances the next_due_date by the config's frequency.
func (w *RecurringWorker) ProcessDueRecurring() error {
	logrus.Info("⏳ [RecurringWorker] Checking for due recurring transactions...")

	configs, err := w.recurringRepo.GetDueConfigs()
	if err != nil {
		logrus.WithError(err).Error("❌ [RecurringWorker] Failed to fetch due recurring configs")
		return err
	}

	if len(configs) == 0 {
		logrus.Info("📭 [RecurringWorker] No recurring transactions due today")
		return nil
	}

	logrus.WithField("count", len(configs)).Info("🔁 [RecurringWorker] Processing due recurring configs")

	var processingErrors int
	for _, config := range configs {
		logEntry := logrus.WithFields(logrus.Fields{
			"config_id":   config.ID,
			"user_id":     config.UserID,
			"frequency":   config.Frequency,
			"next_due":    config.NextDueDate.Format("2006-01-02"),
		})

		// 1. Insert the new transaction
		catID := config.CategoryID
		transaction := &models.Transaction{
			UserID:          config.UserID,
			CategoryID:      &catID,
			Amount:          config.Amount,
			Merchant:        "Recurring Transaction", // Generic merchant label
			Note:            "Auto-generated by recurring schedule",
			TransactionDate: config.NextDueDate,
			MessageID:       nil,  // no email source
			IsRecurring:     true,
		}

		if err := w.transactionRepo.Create(transaction); err != nil {
			logEntry.WithError(err).Error("❌ [RecurringWorker] Failed to create recurring transaction")
			processingErrors++
			continue // keep processing other configs even if one fails
		}

		logEntry.WithField("transaction_id", transaction.ID).Info("✅ [RecurringWorker] Recurring transaction inserted")

		// 2. Advance next_due_date based on frequency
		config.NextDueDate = advanceDate(config.NextDueDate, config.Frequency)

		if err := w.recurringRepo.Update(&config); err != nil {
			logEntry.WithError(err).Error("❌ [RecurringWorker] Failed to update next_due_date for config")
			processingErrors++
			continue
		}

		logEntry.WithField("new_next_due", config.NextDueDate.Format("2006-01-02")).Info("📅 [RecurringWorker] next_due_date advanced")
	}

	if processingErrors > 0 {
		logrus.WithField("error_count", processingErrors).Warn("⚠️ [RecurringWorker] Completed with errors")
	} else {
		logrus.WithField("processed", len(configs)).Info("🎉 [RecurringWorker] All due recurring transactions processed successfully")
	}

	return nil
}

// advanceDate returns a new time.Time advanced by one frequency unit
func advanceDate(t time.Time, frequency string) time.Time {
	switch frequency {
	case "weekly":
		return t.AddDate(0, 0, 7)
	case "yearly":
		return t.AddDate(1, 0, 0)
	default: // "monthly"
		return t.AddDate(0, 1, 0)
	}
}

// Ensure uuid package is used if needed (imported via models indirectly)
var _ = uuid.Nil
