// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: auth.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
insert into public.users (
    google_id, email, name, picture
)
values (
    $1, $2, $3, $4
)
returning id, google_id, email, name, picture,
    created_at, updated_at, deleted_at
`

type CreateUserParams struct {
	GoogleID string  `json:"google_id"`
	Email    string  `json:"email"`
	Name     string  `json:"name"`
	Picture  *string `json:"picture"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.GoogleID,
		arg.Email,
		arg.Name,
		arg.Picture,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GoogleID,
		&i.Email,
		&i.Name,
		&i.Picture,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
select id, google_id, email, name, picture,
    created_at, updated_at, deleted_at
from public.users
where email = $1
  and deleted_at is null
limit 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GoogleID,
		&i.Email,
		&i.Name,
		&i.Picture,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByGoogleID = `-- name: GetUserByGoogleID :one
select id, google_id, email, name, picture,
    created_at, updated_at, deleted_at
from public.users
where google_id = $1
  and deleted_at is null
limit 1
`

func (q *Queries) GetUserByGoogleID(ctx context.Context, googleID string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByGoogleID, googleID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GoogleID,
		&i.Email,
		&i.Name,
		&i.Picture,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
select id, google_id, email, name, picture,
    created_at, updated_at, deleted_at
from public.users
where id = $1
  and deleted_at is null
limit 1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GoogleID,
		&i.Email,
		&i.Name,
		&i.Picture,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
update public.users
set google_id = $1,
    email = $2,
    name = $3,
    picture = $4
where id = $5
returning id, google_id, email, name, picture,
    created_at, updated_at, deleted_at
`

type UpdateUserParams struct {
	GoogleID string      `json:"google_id"`
	Email    string      `json:"email"`
	Name     string      `json:"name"`
	Picture  *string     `json:"picture"`
	ID       pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.GoogleID,
		arg.Email,
		arg.Name,
		arg.Picture,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GoogleID,
		&i.Email,
		&i.Name,
		&i.Picture,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
