// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: budget.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCategoryLimit = `-- name: CreateCategoryLimit :one
insert into public.category_limits (
    user_id, category_id, period, limit_amount, is_active
)
values (
    $1,
    $2,
    coalesce(nullif($3::text, ''), 'monthly'),
    $4,
    $5
)
returning id, user_id, category_id, period, limit_amount, is_active,
    created_at, updated_at
`

type CreateCategoryLimitParams struct {
	UserID      pgtype.UUID `json:"user_id"`
	CategoryID  pgtype.UUID `json:"category_id"`
	Period      string      `json:"period"`
	LimitAmount float64     `json:"limit_amount"`
	IsActive    bool        `json:"is_active"`
}

func (q *Queries) CreateCategoryLimit(ctx context.Context, arg CreateCategoryLimitParams) (CategoryLimit, error) {
	row := q.db.QueryRow(ctx, createCategoryLimit,
		arg.UserID,
		arg.CategoryID,
		arg.Period,
		arg.LimitAmount,
		arg.IsActive,
	)
	var i CategoryLimit
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CategoryID,
		&i.Period,
		&i.LimitAmount,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCategoryLimit = `-- name: DeleteCategoryLimit :execrows
delete from public.category_limits
where id = $1
  and user_id = $2
`

type DeleteCategoryLimitParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) DeleteCategoryLimit(ctx context.Context, arg DeleteCategoryLimitParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCategoryLimit, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCategoryLimitByCategory = `-- name: GetCategoryLimitByCategory :one
select id, user_id, category_id, period, limit_amount, is_active,
    created_at, updated_at
from public.category_limits
where user_id = $1
  and category_id = $2
limit 1
`

type GetCategoryLimitByCategoryParams struct {
	UserID     pgtype.UUID `json:"user_id"`
	CategoryID pgtype.UUID `json:"category_id"`
}

func (q *Queries) GetCategoryLimitByCategory(ctx context.Context, arg GetCategoryLimitByCategoryParams) (CategoryLimit, error) {
	row := q.db.QueryRow(ctx, getCategoryLimitByCategory, arg.UserID, arg.CategoryID)
	var i CategoryLimit
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CategoryID,
		&i.Period,
		&i.LimitAmount,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCategoryLimitByID = `-- name: GetCategoryLimitByID :one
select id, user_id, category_id, period, limit_amount, is_active,
    created_at, updated_at
from public.category_limits
where id = $1
  and user_id = $2
limit 1
`

type GetCategoryLimitByIDParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetCategoryLimitByID(ctx context.Context, arg GetCategoryLimitByIDParams) (CategoryLimit, error) {
	row := q.db.QueryRow(ctx, getCategoryLimitByID, arg.ID, arg.UserID)
	var i CategoryLimit
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CategoryID,
		&i.Period,
		&i.LimitAmount,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDailyTotalByUserAndRange = `-- name: GetDailyTotalByUserAndRange :many
select day, sum(total_amount)::numeric as total_amount
from public.daily_expense_summary
where user_id = $1
  and day >= $2
  and day < $3
group by day
order by day asc
`

type GetDailyTotalByUserAndRangeParams struct {
	UserID    pgtype.UUID `json:"user_id"`
	StartDate pgtype.Date `json:"start_date"`
	EndDate   pgtype.Date `json:"end_date"`
}

type GetDailyTotalByUserAndRangeRow struct {
	Day         pgtype.Date `json:"day"`
	TotalAmount float64     `json:"total_amount"`
}

func (q *Queries) GetDailyTotalByUserAndRange(ctx context.Context, arg GetDailyTotalByUserAndRangeParams) ([]GetDailyTotalByUserAndRangeRow, error) {
	rows, err := q.db.Query(ctx, getDailyTotalByUserAndRange, arg.UserID, arg.StartDate, arg.EndDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetDailyTotalByUserAndRangeRow{}
	for rows.Next() {
		var i GetDailyTotalByUserAndRangeRow
		if err := rows.Scan(&i.Day, &i.TotalAmount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLimitReportByUserID = `-- name: GetLimitReportByUserID :many
select
    c.name as category_name,
    c.icon as category_icon,
    cl.limit_amount,
    coalesce(sum(t.amount), 0)::numeric as total_spent
from public.category_limits cl
join public.categories c on c.id = cl.category_id
left join public.transactions t
    on t.category_id = cl.category_id
   and t.user_id = cl.user_id
   and t.deleted_at is null
   and date_trunc('month', t.transaction_date at time zone 'Asia/Jakarta') =
       date_trunc('month', now() at time zone 'Asia/Jakarta')
where cl.user_id = $1
  and cl.is_active = true
  and c.deleted_at is null
group by c.id, c.name, c.icon, cl.id, cl.limit_amount
order by c.name asc
`

type GetLimitReportByUserIDRow struct {
	CategoryName string  `json:"category_name"`
	CategoryIcon string  `json:"category_icon"`
	LimitAmount  float64 `json:"limit_amount"`
	TotalSpent   float64 `json:"total_spent"`
}

func (q *Queries) GetLimitReportByUserID(ctx context.Context, userID pgtype.UUID) ([]GetLimitReportByUserIDRow, error) {
	rows, err := q.db.Query(ctx, getLimitReportByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetLimitReportByUserIDRow{}
	for rows.Next() {
		var i GetLimitReportByUserIDRow
		if err := rows.Scan(
			&i.CategoryName,
			&i.CategoryIcon,
			&i.LimitAmount,
			&i.TotalSpent,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSpendingByCategoryAndRange = `-- name: GetSpendingByCategoryAndRange :many
select category_id, sum(total_amount)::numeric as total_amount,
    sum(transaction_count)::bigint as transaction_count
from public.daily_expense_summary
where user_id = $1
  and day >= $2
  and day <= $3
group by category_id
`

type GetSpendingByCategoryAndRangeParams struct {
	UserID    pgtype.UUID `json:"user_id"`
	StartDate pgtype.Date `json:"start_date"`
	EndDate   pgtype.Date `json:"end_date"`
}

type GetSpendingByCategoryAndRangeRow struct {
	CategoryID       pgtype.UUID `json:"category_id"`
	TotalAmount      float64     `json:"total_amount"`
	TransactionCount int64       `json:"transaction_count"`
}

func (q *Queries) GetSpendingByCategoryAndRange(ctx context.Context, arg GetSpendingByCategoryAndRangeParams) ([]GetSpendingByCategoryAndRangeRow, error) {
	rows, err := q.db.Query(ctx, getSpendingByCategoryAndRange, arg.UserID, arg.StartDate, arg.EndDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetSpendingByCategoryAndRangeRow{}
	for rows.Next() {
		var i GetSpendingByCategoryAndRangeRow
		if err := rows.Scan(&i.CategoryID, &i.TotalAmount, &i.TransactionCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSummaryByUserAndStartDate = `-- name: GetSummaryByUserAndStartDate :many
select category_id, sum(total_amount)::numeric as total_amount,
    sum(transaction_count)::bigint as transaction_count
from public.daily_expense_summary
where user_id = $1
  and day >= $2
group by category_id
`

type GetSummaryByUserAndStartDateParams struct {
	UserID    pgtype.UUID `json:"user_id"`
	StartDate pgtype.Date `json:"start_date"`
}

type GetSummaryByUserAndStartDateRow struct {
	CategoryID       pgtype.UUID `json:"category_id"`
	TotalAmount      float64     `json:"total_amount"`
	TransactionCount int64       `json:"transaction_count"`
}

func (q *Queries) GetSummaryByUserAndStartDate(ctx context.Context, arg GetSummaryByUserAndStartDateParams) ([]GetSummaryByUserAndStartDateRow, error) {
	rows, err := q.db.Query(ctx, getSummaryByUserAndStartDate, arg.UserID, arg.StartDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetSummaryByUserAndStartDateRow{}
	for rows.Next() {
		var i GetSummaryByUserAndStartDateRow
		if err := rows.Scan(&i.CategoryID, &i.TotalAmount, &i.TransactionCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveCategoryLimitsWithCategory = `-- name: ListActiveCategoryLimitsWithCategory :many
select
    cl.id, cl.user_id, cl.category_id, cl.period, cl.limit_amount,
    cl.is_active, cl.created_at, cl.updated_at,
    c.name as category_name, c.icon as category_icon
from public.category_limits cl
join public.categories c on c.id = cl.category_id
where cl.user_id = $1
  and cl.is_active = true
  and c.deleted_at is null
order by cl.created_at desc
`

type ListActiveCategoryLimitsWithCategoryRow struct {
	ID           pgtype.UUID        `json:"id"`
	UserID       pgtype.UUID        `json:"user_id"`
	CategoryID   pgtype.UUID        `json:"category_id"`
	Period       string             `json:"period"`
	LimitAmount  float64            `json:"limit_amount"`
	IsActive     bool               `json:"is_active"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	CategoryName string             `json:"category_name"`
	CategoryIcon string             `json:"category_icon"`
}

func (q *Queries) ListActiveCategoryLimitsWithCategory(ctx context.Context, userID pgtype.UUID) ([]ListActiveCategoryLimitsWithCategoryRow, error) {
	rows, err := q.db.Query(ctx, listActiveCategoryLimitsWithCategory, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveCategoryLimitsWithCategoryRow{}
	for rows.Next() {
		var i ListActiveCategoryLimitsWithCategoryRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CategoryID,
			&i.Period,
			&i.LimitAmount,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CategoryName,
			&i.CategoryIcon,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCategoryLimits = `-- name: ListCategoryLimits :many
select id, user_id, category_id, period, limit_amount, is_active,
    created_at, updated_at
from public.category_limits
where user_id = $1
order by created_at desc
`

func (q *Queries) ListCategoryLimits(ctx context.Context, userID pgtype.UUID) ([]CategoryLimit, error) {
	rows, err := q.db.Query(ctx, listCategoryLimits, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CategoryLimit{}
	for rows.Next() {
		var i CategoryLimit
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CategoryID,
			&i.Period,
			&i.LimitAmount,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCategoryLimit = `-- name: UpdateCategoryLimit :one
update public.category_limits
set period = $1,
    limit_amount = $2,
    is_active = $3
where id = $4
  and user_id = $5
returning id, user_id, category_id, period, limit_amount, is_active,
    created_at, updated_at
`

type UpdateCategoryLimitParams struct {
	Period      string      `json:"period"`
	LimitAmount float64     `json:"limit_amount"`
	IsActive    bool        `json:"is_active"`
	ID          pgtype.UUID `json:"id"`
	UserID      pgtype.UUID `json:"user_id"`
}

func (q *Queries) UpdateCategoryLimit(ctx context.Context, arg UpdateCategoryLimitParams) (CategoryLimit, error) {
	row := q.db.QueryRow(ctx, updateCategoryLimit,
		arg.Period,
		arg.LimitAmount,
		arg.IsActive,
		arg.ID,
		arg.UserID,
	)
	var i CategoryLimit
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CategoryID,
		&i.Period,
		&i.LimitAmount,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
