// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: categories.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCategory = `-- name: CreateCategory :one
insert into public.categories (user_id, name, type)
values ($1, $2, $3)
returning id, user_id, name, type, created_at, updated_at
`

type CreateCategoryParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Name   string      `json:"name"`
	Type   string      `json:"type"`
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, createCategory, arg.UserID, arg.Name, arg.Type)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Type,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCategory = `-- name: DeleteCategory :execrows
delete from public.categories
where id = $1
  and user_id = $2
`

type DeleteCategoryParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) DeleteCategory(ctx context.Context, arg DeleteCategoryParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCategory, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listCategoriesByUser = `-- name: ListCategoriesByUser :many
select id, user_id, name, type, created_at, updated_at
from public.categories
where user_id = $1
  and (
      $2::text is null
      or type = $2::text
  )
order by type asc, name asc, id asc
`

type ListCategoriesByUserParams struct {
	UserID       pgtype.UUID `json:"user_id"`
	CategoryType *string     `json:"category_type"`
}

func (q *Queries) ListCategoriesByUser(ctx context.Context, arg ListCategoriesByUserParams) ([]Category, error) {
	rows, err := q.db.Query(ctx, listCategoriesByUser, arg.UserID, arg.CategoryType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Type,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCategory = `-- name: UpdateCategory :one
update public.categories
set name = $1,
    type = $2,
    updated_at = now()
where id = $3
  and user_id = $4
returning id, user_id, name, type, created_at, updated_at
`

type UpdateCategoryParams struct {
	Name   string      `json:"name"`
	Type   string      `json:"type"`
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, updateCategory,
		arg.Name,
		arg.Type,
		arg.ID,
		arg.UserID,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Type,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
