// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: categories.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCategory = `-- name: CreateCategory :one
insert into public.categories (user_id, name, icon)
values ($1, $2, $3::text)
returning id, user_id, name, icon, created_at, updated_at, deleted_at
`

type CreateCategoryParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Name   string      `json:"name"`
	Icon   string      `json:"icon"`
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, createCategory, arg.UserID, arg.Name, arg.Icon)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Icon,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getCategoryByID = `-- name: GetCategoryByID :one
select id, user_id, name, icon, created_at, updated_at, deleted_at
from public.categories
where id = $1
  and user_id = $2
  and deleted_at is null
limit 1
`

type GetCategoryByIDParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetCategoryByID(ctx context.Context, arg GetCategoryByIDParams) (Category, error) {
	row := q.db.QueryRow(ctx, getCategoryByID, arg.ID, arg.UserID)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Icon,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getCategoryByName = `-- name: GetCategoryByName :one
select id, user_id, name, icon, created_at, updated_at, deleted_at
from public.categories
where lower(name) = lower($1)
  and user_id = $2
  and deleted_at is null
limit 1
`

type GetCategoryByNameParams struct {
	Name   string      `json:"name"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetCategoryByName(ctx context.Context, arg GetCategoryByNameParams) (Category, error) {
	row := q.db.QueryRow(ctx, getCategoryByName, arg.Name, arg.UserID)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Icon,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listCategories = `-- name: ListCategories :many
select id, user_id, name, icon, created_at, updated_at, deleted_at
from public.categories
where user_id = $1
  and deleted_at is null
order by created_at desc
`

func (q *Queries) ListCategories(ctx context.Context, userID pgtype.UUID) ([]Category, error) {
	rows, err := q.db.Query(ctx, listCategories, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Icon,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteCategory = `-- name: SoftDeleteCategory :execrows
update public.categories
set deleted_at = now()
where id = $1
  and user_id = $2
  and deleted_at is null
`

type SoftDeleteCategoryParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) SoftDeleteCategory(ctx context.Context, arg SoftDeleteCategoryParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteCategory, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateCategory = `-- name: UpdateCategory :one
update public.categories
set name = $1, icon = $2
where id = $3
  and user_id = $4
  and deleted_at is null
returning id, user_id, name, icon, created_at, updated_at, deleted_at
`

type UpdateCategoryParams struct {
	Name   string      `json:"name"`
	Icon   string      `json:"icon"`
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, updateCategory,
		arg.Name,
		arg.Icon,
		arg.ID,
		arg.UserID,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Icon,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
