// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Category struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Name      string             `json:"name"`
	Icon      string             `json:"icon"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

type CategoryLimit struct {
	ID          pgtype.UUID        `json:"id"`
	UserID      pgtype.UUID        `json:"user_id"`
	CategoryID  pgtype.UUID        `json:"category_id"`
	Period      string             `json:"period"`
	LimitAmount float64            `json:"limit_amount"`
	IsActive    bool               `json:"is_active"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type DailyExpenseSummary struct {
	UserID           pgtype.UUID `json:"user_id"`
	Day              pgtype.Date `json:"day"`
	CategoryID       pgtype.UUID `json:"category_id"`
	TotalAmount      int64       `json:"total_amount"`
	TransactionCount int64       `json:"transaction_count"`
}

type RecurringConfig struct {
	ID          pgtype.UUID        `json:"id"`
	UserID      pgtype.UUID        `json:"user_id"`
	CategoryID  pgtype.UUID        `json:"category_id"`
	Amount      float64            `json:"amount"`
	Frequency   string             `json:"frequency"`
	StartDate   pgtype.Timestamptz `json:"start_date"`
	NextDueDate pgtype.Timestamptz `json:"next_due_date"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Transaction struct {
	ID              pgtype.UUID        `json:"id"`
	UserID          pgtype.UUID        `json:"user_id"`
	CategoryID      pgtype.UUID        `json:"category_id"`
	Amount          float64            `json:"amount"`
	Merchant        string             `json:"merchant"`
	Note            string             `json:"note"`
	TransactionDate pgtype.Timestamptz `json:"transaction_date"`
	MessageID       *string            `json:"message_id"`
	IsRecurring     bool               `json:"is_recurring"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
}

type User struct {
	ID             pgtype.UUID        `json:"id"`
	GoogleID       string             `json:"google_id"`
	Email          string             `json:"email"`
	Name           string             `json:"name"`
	Picture        *string            `json:"picture"`
	TelegramChatID *string            `json:"telegram_chat_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	DeletedAt      pgtype.Timestamptz `json:"deleted_at"`
}
