// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteCategory(ctx context.Context, arg DeleteCategoryParams) (int64, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByGoogleID(ctx context.Context, googleID string) (User, error)
	GetUserByGoogleIDAny(ctx context.Context, googleID string) (User, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	ListCategoriesByUser(ctx context.Context, arg ListCategoriesByUserParams) ([]Category, error)
	Ping(ctx context.Context) (int32, error)
	SoftDeleteUser(ctx context.Context, id pgtype.UUID) (int64, error)
	UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateUserGoogleProfile(ctx context.Context, arg UpdateUserGoogleProfileParams) (User, error)
	UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error)
}

var _ Querier = (*Queries)(nil)
