// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CountSearchTransactions(ctx context.Context, arg CountSearchTransactionsParams) (int64, error)
	CountTransactions(ctx context.Context, arg CountTransactionsParams) (int64, error)
	CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error)
	CreateCategoryLimit(ctx context.Context, arg CreateCategoryLimitParams) (CategoryLimit, error)
	CreateRecurringConfig(ctx context.Context, arg CreateRecurringConfigParams) (RecurringConfig, error)
	CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteCategoryLimit(ctx context.Context, arg DeleteCategoryLimitParams) (int64, error)
	DeleteRecurringConfig(ctx context.Context, arg DeleteRecurringConfigParams) (int64, error)
	GetCategoryByID(ctx context.Context, arg GetCategoryByIDParams) (Category, error)
	GetCategoryByName(ctx context.Context, arg GetCategoryByNameParams) (Category, error)
	GetCategoryLimitByCategory(ctx context.Context, arg GetCategoryLimitByCategoryParams) (CategoryLimit, error)
	GetCategoryLimitByID(ctx context.Context, arg GetCategoryLimitByIDParams) (CategoryLimit, error)
	GetDailyTotalByUserAndRange(ctx context.Context, arg GetDailyTotalByUserAndRangeParams) ([]GetDailyTotalByUserAndRangeRow, error)
	GetExpensesByCategory(ctx context.Context, arg GetExpensesByCategoryParams) ([]GetExpensesByCategoryRow, error)
	GetLimitReportByUserID(ctx context.Context, userID pgtype.UUID) ([]GetLimitReportByUserIDRow, error)
	GetRecurringConfigByID(ctx context.Context, arg GetRecurringConfigByIDParams) (RecurringConfig, error)
	GetSpendingByCategoryAndRange(ctx context.Context, arg GetSpendingByCategoryAndRangeParams) ([]GetSpendingByCategoryAndRangeRow, error)
	GetSummaryByUserAndStartDate(ctx context.Context, arg GetSummaryByUserAndStartDateParams) ([]GetSummaryByUserAndStartDateRow, error)
	GetTotalSpentByCategory(ctx context.Context, arg GetTotalSpentByCategoryParams) (float64, error)
	GetTransactionByID(ctx context.Context, id pgtype.UUID) (Transaction, error)
	GetTransactionByMessageID(ctx context.Context, messageID *string) (Transaction, error)
	GetTransactionsForExport(ctx context.Context, arg GetTransactionsForExportParams) ([]GetTransactionsForExportRow, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByGoogleID(ctx context.Context, googleID string) (User, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	GetUserByTelegramChatID(ctx context.Context, telegramChatID *string) (User, error)
	ListActiveCategoryLimitsWithCategory(ctx context.Context, userID pgtype.UUID) ([]ListActiveCategoryLimitsWithCategoryRow, error)
	ListCategories(ctx context.Context, userID pgtype.UUID) ([]Category, error)
	ListCategoryLimits(ctx context.Context, userID pgtype.UUID) ([]CategoryLimit, error)
	ListDueRecurringConfigs(ctx context.Context) ([]RecurringConfig, error)
	ListRecurringConfigs(ctx context.Context, userID pgtype.UUID) ([]RecurringConfig, error)
	ListTransactions(ctx context.Context, arg ListTransactionsParams) ([]Transaction, error)
	Ping(ctx context.Context) (int32, error)
	SearchTransactions(ctx context.Context, arg SearchTransactionsParams) ([]Transaction, error)
	SoftDeleteCategory(ctx context.Context, arg SoftDeleteCategoryParams) (int64, error)
	SoftDeleteTransaction(ctx context.Context, id pgtype.UUID) (int64, error)
	UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error)
	UpdateCategoryLimit(ctx context.Context, arg UpdateCategoryLimitParams) (CategoryLimit, error)
	UpdateRecurringConfig(ctx context.Context, arg UpdateRecurringConfigParams) (RecurringConfig, error)
	UpdateTransaction(ctx context.Context, arg UpdateTransactionParams) (Transaction, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
