// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: recurring.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRecurringConfig = `-- name: CreateRecurringConfig :one
insert into public.recurring_configs (
    user_id, category_id, amount, frequency, start_date, next_due_date
)
values (
    $1, $2, $3,
    $4, $5, $6
)
returning id, user_id, category_id, amount, frequency, start_date,
    next_due_date, created_at, updated_at
`

type CreateRecurringConfigParams struct {
	UserID      pgtype.UUID        `json:"user_id"`
	CategoryID  pgtype.UUID        `json:"category_id"`
	Amount      float64            `json:"amount"`
	Frequency   string             `json:"frequency"`
	StartDate   pgtype.Timestamptz `json:"start_date"`
	NextDueDate pgtype.Timestamptz `json:"next_due_date"`
}

func (q *Queries) CreateRecurringConfig(ctx context.Context, arg CreateRecurringConfigParams) (RecurringConfig, error) {
	row := q.db.QueryRow(ctx, createRecurringConfig,
		arg.UserID,
		arg.CategoryID,
		arg.Amount,
		arg.Frequency,
		arg.StartDate,
		arg.NextDueDate,
	)
	var i RecurringConfig
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CategoryID,
		&i.Amount,
		&i.Frequency,
		&i.StartDate,
		&i.NextDueDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteRecurringConfig = `-- name: DeleteRecurringConfig :execrows
delete from public.recurring_configs
where id = $1
  and user_id = $2
`

type DeleteRecurringConfigParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) DeleteRecurringConfig(ctx context.Context, arg DeleteRecurringConfigParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteRecurringConfig, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getRecurringConfigByID = `-- name: GetRecurringConfigByID :one
select id, user_id, category_id, amount, frequency, start_date,
    next_due_date, created_at, updated_at
from public.recurring_configs
where id = $1
  and user_id = $2
limit 1
`

type GetRecurringConfigByIDParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetRecurringConfigByID(ctx context.Context, arg GetRecurringConfigByIDParams) (RecurringConfig, error) {
	row := q.db.QueryRow(ctx, getRecurringConfigByID, arg.ID, arg.UserID)
	var i RecurringConfig
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CategoryID,
		&i.Amount,
		&i.Frequency,
		&i.StartDate,
		&i.NextDueDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDueRecurringConfigs = `-- name: ListDueRecurringConfigs :many
select id, user_id, category_id, amount, frequency, start_date,
    next_due_date, created_at, updated_at
from public.recurring_configs
where next_due_date <= now()
order by next_due_date asc
`

func (q *Queries) ListDueRecurringConfigs(ctx context.Context) ([]RecurringConfig, error) {
	rows, err := q.db.Query(ctx, listDueRecurringConfigs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RecurringConfig{}
	for rows.Next() {
		var i RecurringConfig
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CategoryID,
			&i.Amount,
			&i.Frequency,
			&i.StartDate,
			&i.NextDueDate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecurringConfigs = `-- name: ListRecurringConfigs :many
select id, user_id, category_id, amount, frequency, start_date,
    next_due_date, created_at, updated_at
from public.recurring_configs
where user_id = $1
order by created_at desc
`

func (q *Queries) ListRecurringConfigs(ctx context.Context, userID pgtype.UUID) ([]RecurringConfig, error) {
	rows, err := q.db.Query(ctx, listRecurringConfigs, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RecurringConfig{}
	for rows.Next() {
		var i RecurringConfig
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CategoryID,
			&i.Amount,
			&i.Frequency,
			&i.StartDate,
			&i.NextDueDate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRecurringConfig = `-- name: UpdateRecurringConfig :one
update public.recurring_configs
set category_id = $1,
    amount = $2,
    frequency = $3,
    start_date = $4,
    next_due_date = $5
where id = $6
  and user_id = $7
returning id, user_id, category_id, amount, frequency, start_date,
    next_due_date, created_at, updated_at
`

type UpdateRecurringConfigParams struct {
	CategoryID  pgtype.UUID        `json:"category_id"`
	Amount      float64            `json:"amount"`
	Frequency   string             `json:"frequency"`
	StartDate   pgtype.Timestamptz `json:"start_date"`
	NextDueDate pgtype.Timestamptz `json:"next_due_date"`
	ID          pgtype.UUID        `json:"id"`
	UserID      pgtype.UUID        `json:"user_id"`
}

func (q *Queries) UpdateRecurringConfig(ctx context.Context, arg UpdateRecurringConfigParams) (RecurringConfig, error) {
	row := q.db.QueryRow(ctx, updateRecurringConfig,
		arg.CategoryID,
		arg.Amount,
		arg.Frequency,
		arg.StartDate,
		arg.NextDueDate,
		arg.ID,
		arg.UserID,
	)
	var i RecurringConfig
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CategoryID,
		&i.Amount,
		&i.Frequency,
		&i.StartDate,
		&i.NextDueDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
