// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: transactions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countSearchTransactions = `-- name: CountSearchTransactions :one
select count(*)::bigint
from public.transactions
where user_id = $1
  and merchant ilike '%' || $2 || '%'
  and deleted_at is null
`

type CountSearchTransactionsParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Query  *string     `json:"query"`
}

func (q *Queries) CountSearchTransactions(ctx context.Context, arg CountSearchTransactionsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countSearchTransactions, arg.UserID, arg.Query)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countTransactions = `-- name: CountTransactions :one
select count(*)::bigint
from public.transactions
where user_id = $1
  and (nullif($2::text, '') is null
       or transaction_date::date >= nullif($2::text, '')::date)
  and (nullif($3::text, '') is null
       or transaction_date::date <= nullif($3::text, '')::date)
  and (nullif($4::text, '') is null
       or amount >= nullif($4::text, '')::numeric)
  and (nullif($5::text, '') is null
       or amount <= nullif($5::text, '')::numeric)
  and (nullif($6::text, '') is null
       or updated_at > nullif($6::text, '')::timestamptz)
  and (not $7::boolean or deleted_at is null)
`

type CountTransactionsParams struct {
	UserID         pgtype.UUID `json:"user_id"`
	DateFrom       string      `json:"date_from"`
	DateTo         string      `json:"date_to"`
	AmountMin      string      `json:"amount_min"`
	AmountMax      string      `json:"amount_max"`
	LastUpdated    string      `json:"last_updated"`
	ExcludeDeleted bool        `json:"exclude_deleted"`
}

func (q *Queries) CountTransactions(ctx context.Context, arg CountTransactionsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countTransactions,
		arg.UserID,
		arg.DateFrom,
		arg.DateTo,
		arg.AmountMin,
		arg.AmountMax,
		arg.LastUpdated,
		arg.ExcludeDeleted,
	)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createTransaction = `-- name: CreateTransaction :one
insert into public.transactions (
    user_id, category_id, amount, merchant, note, transaction_date,
    message_id, is_recurring
)
values (
    $1, $2, $3,
    $4, coalesce($5::text, ''),
    $6, $7, $8
)
returning id, user_id, category_id, amount, merchant, note,
    transaction_date, message_id, is_recurring, created_at, updated_at,
    deleted_at
`

type CreateTransactionParams struct {
	UserID          pgtype.UUID        `json:"user_id"`
	CategoryID      pgtype.UUID        `json:"category_id"`
	Amount          float64            `json:"amount"`
	Merchant        string             `json:"merchant"`
	Note            *string            `json:"note"`
	TransactionDate pgtype.Timestamptz `json:"transaction_date"`
	MessageID       *string            `json:"message_id"`
	IsRecurring     bool               `json:"is_recurring"`
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, createTransaction,
		arg.UserID,
		arg.CategoryID,
		arg.Amount,
		arg.Merchant,
		arg.Note,
		arg.TransactionDate,
		arg.MessageID,
		arg.IsRecurring,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CategoryID,
		&i.Amount,
		&i.Merchant,
		&i.Note,
		&i.TransactionDate,
		&i.MessageID,
		&i.IsRecurring,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getExpensesByCategory = `-- name: GetExpensesByCategory :many
select c.name as category_name, sum(t.amount)::numeric as total_amount
from public.transactions t
left join public.categories c on c.id = t.category_id
where t.user_id = $1
  and t.transaction_date >= $2
  and t.transaction_date < $3
  and t.deleted_at is null
group by c.name
order by total_amount desc
`

type GetExpensesByCategoryParams struct {
	UserID    pgtype.UUID        `json:"user_id"`
	StartDate pgtype.Timestamptz `json:"start_date"`
	EndDate   pgtype.Timestamptz `json:"end_date"`
}

type GetExpensesByCategoryRow struct {
	CategoryName *string `json:"category_name"`
	TotalAmount  float64 `json:"total_amount"`
}

func (q *Queries) GetExpensesByCategory(ctx context.Context, arg GetExpensesByCategoryParams) ([]GetExpensesByCategoryRow, error) {
	rows, err := q.db.Query(ctx, getExpensesByCategory, arg.UserID, arg.StartDate, arg.EndDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetExpensesByCategoryRow{}
	for rows.Next() {
		var i GetExpensesByCategoryRow
		if err := rows.Scan(&i.CategoryName, &i.TotalAmount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTotalSpentByCategory = `-- name: GetTotalSpentByCategory :one
select coalesce(sum(amount), 0)::numeric as total_spent
from public.transactions
where user_id = $1
  and category_id = $2
  and transaction_date >= $3
  and transaction_date < $4
  and deleted_at is null
`

type GetTotalSpentByCategoryParams struct {
	UserID     pgtype.UUID        `json:"user_id"`
	CategoryID pgtype.UUID        `json:"category_id"`
	StartDate  pgtype.Timestamptz `json:"start_date"`
	EndDate    pgtype.Timestamptz `json:"end_date"`
}

func (q *Queries) GetTotalSpentByCategory(ctx context.Context, arg GetTotalSpentByCategoryParams) (float64, error) {
	row := q.db.QueryRow(ctx, getTotalSpentByCategory,
		arg.UserID,
		arg.CategoryID,
		arg.StartDate,
		arg.EndDate,
	)
	var total_spent float64
	err := row.Scan(&total_spent)
	return total_spent, err
}

const getTransactionByID = `-- name: GetTransactionByID :one
select id, user_id, category_id, amount, merchant, note,
    transaction_date, message_id, is_recurring, created_at, updated_at,
    deleted_at
from public.transactions
where id = $1
  and deleted_at is null
limit 1
`

func (q *Queries) GetTransactionByID(ctx context.Context, id pgtype.UUID) (Transaction, error) {
	row := q.db.QueryRow(ctx, getTransactionByID, id)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CategoryID,
		&i.Amount,
		&i.Merchant,
		&i.Note,
		&i.TransactionDate,
		&i.MessageID,
		&i.IsRecurring,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getTransactionByMessageID = `-- name: GetTransactionByMessageID :one
select id, user_id, category_id, amount, merchant, note,
    transaction_date, message_id, is_recurring, created_at, updated_at,
    deleted_at
from public.transactions
where message_id = $1
  and deleted_at is null
limit 1
`

func (q *Queries) GetTransactionByMessageID(ctx context.Context, messageID *string) (Transaction, error) {
	row := q.db.QueryRow(ctx, getTransactionByMessageID, messageID)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CategoryID,
		&i.Amount,
		&i.Merchant,
		&i.Note,
		&i.TransactionDate,
		&i.MessageID,
		&i.IsRecurring,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getTransactionsForExport = `-- name: GetTransactionsForExport :many
select
    t.id, t.user_id, t.category_id, t.amount, t.merchant, t.note,
    t.transaction_date, t.message_id, t.is_recurring, t.created_at,
    t.updated_at, t.deleted_at,
    c.name as category_name, c.icon as category_icon
from public.transactions t
left join public.categories c on c.id = t.category_id
where t.user_id = $1
  and t.transaction_date >= $2
  and t.transaction_date < $3
  and t.deleted_at is null
order by t.transaction_date asc
`

type GetTransactionsForExportParams struct {
	UserID    pgtype.UUID        `json:"user_id"`
	StartDate pgtype.Timestamptz `json:"start_date"`
	EndDate   pgtype.Timestamptz `json:"end_date"`
}

type GetTransactionsForExportRow struct {
	ID              pgtype.UUID        `json:"id"`
	UserID          pgtype.UUID        `json:"user_id"`
	CategoryID      pgtype.UUID        `json:"category_id"`
	Amount          float64            `json:"amount"`
	Merchant        string             `json:"merchant"`
	Note            string             `json:"note"`
	TransactionDate pgtype.Timestamptz `json:"transaction_date"`
	MessageID       *string            `json:"message_id"`
	IsRecurring     bool               `json:"is_recurring"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
	CategoryName    *string            `json:"category_name"`
	CategoryIcon    *string            `json:"category_icon"`
}

func (q *Queries) GetTransactionsForExport(ctx context.Context, arg GetTransactionsForExportParams) ([]GetTransactionsForExportRow, error) {
	rows, err := q.db.Query(ctx, getTransactionsForExport, arg.UserID, arg.StartDate, arg.EndDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTransactionsForExportRow{}
	for rows.Next() {
		var i GetTransactionsForExportRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CategoryID,
			&i.Amount,
			&i.Merchant,
			&i.Note,
			&i.TransactionDate,
			&i.MessageID,
			&i.IsRecurring,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.CategoryName,
			&i.CategoryIcon,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactions = `-- name: ListTransactions :many
select id, user_id, category_id, amount, merchant, note,
    transaction_date, message_id, is_recurring, created_at, updated_at,
    deleted_at
from public.transactions
where user_id = $1
  and (nullif($2::text, '') is null
       or transaction_date::date >= nullif($2::text, '')::date)
  and (nullif($3::text, '') is null
       or transaction_date::date <= nullif($3::text, '')::date)
  and (nullif($4::text, '') is null
       or amount >= nullif($4::text, '')::numeric)
  and (nullif($5::text, '') is null
       or amount <= nullif($5::text, '')::numeric)
  and (nullif($6::text, '') is null
       or updated_at > nullif($6::text, '')::timestamptz)
  and (not $7::boolean or deleted_at is null)
order by
    case when $8::text = 'transaction_date'
              and $9::text = 'ASC'
         then transaction_date end asc,
    case when $8::text = 'transaction_date'
              and $9::text <> 'ASC'
         then transaction_date end desc,
    case when $8::text = 'amount'
              and $9::text = 'ASC'
         then amount end asc,
    case when $8::text = 'amount'
              and $9::text <> 'ASC'
         then amount end desc,
    case when $8::text = 'merchant'
              and $9::text = 'ASC'
         then merchant end asc,
    case when $8::text = 'merchant'
              and $9::text <> 'ASC'
         then merchant end desc,
    id desc
limit $11
offset $10
`

type ListTransactionsParams struct {
	UserID         pgtype.UUID `json:"user_id"`
	DateFrom       string      `json:"date_from"`
	DateTo         string      `json:"date_to"`
	AmountMin      string      `json:"amount_min"`
	AmountMax      string      `json:"amount_max"`
	LastUpdated    string      `json:"last_updated"`
	ExcludeDeleted bool        `json:"exclude_deleted"`
	SortField      string      `json:"sort_field"`
	SortDirection  string      `json:"sort_direction"`
	OffsetCount    int32       `json:"offset_count"`
	LimitCount     int32       `json:"limit_count"`
}

func (q *Queries) ListTransactions(ctx context.Context, arg ListTransactionsParams) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, listTransactions,
		arg.UserID,
		arg.DateFrom,
		arg.DateTo,
		arg.AmountMin,
		arg.AmountMax,
		arg.LastUpdated,
		arg.ExcludeDeleted,
		arg.SortField,
		arg.SortDirection,
		arg.OffsetCount,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transaction{}
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CategoryID,
			&i.Amount,
			&i.Merchant,
			&i.Note,
			&i.TransactionDate,
			&i.MessageID,
			&i.IsRecurring,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchTransactions = `-- name: SearchTransactions :many
select id, user_id, category_id, amount, merchant, note,
    transaction_date, message_id, is_recurring, created_at, updated_at,
    deleted_at
from public.transactions
where user_id = $1
  and merchant ilike '%' || $2 || '%'
  and deleted_at is null
order by transaction_date desc
limit $4
offset $3
`

type SearchTransactionsParams struct {
	UserID      pgtype.UUID `json:"user_id"`
	Query       *string     `json:"query"`
	OffsetCount int32       `json:"offset_count"`
	LimitCount  int32       `json:"limit_count"`
}

func (q *Queries) SearchTransactions(ctx context.Context, arg SearchTransactionsParams) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, searchTransactions,
		arg.UserID,
		arg.Query,
		arg.OffsetCount,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transaction{}
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CategoryID,
			&i.Amount,
			&i.Merchant,
			&i.Note,
			&i.TransactionDate,
			&i.MessageID,
			&i.IsRecurring,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteTransaction = `-- name: SoftDeleteTransaction :execrows
update public.transactions
set deleted_at = now()
where id = $1
  and deleted_at is null
`

func (q *Queries) SoftDeleteTransaction(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteTransaction, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateTransaction = `-- name: UpdateTransaction :one
update public.transactions
set category_id = $1,
    amount = $2,
    merchant = $3,
    note = $4,
    transaction_date = $5,
    message_id = $6,
    is_recurring = $7
where id = $8
  and deleted_at is null
returning id, user_id, category_id, amount, merchant, note,
    transaction_date, message_id, is_recurring, created_at, updated_at,
    deleted_at
`

type UpdateTransactionParams struct {
	CategoryID      pgtype.UUID        `json:"category_id"`
	Amount          float64            `json:"amount"`
	Merchant        string             `json:"merchant"`
	Note            string             `json:"note"`
	TransactionDate pgtype.Timestamptz `json:"transaction_date"`
	MessageID       *string            `json:"message_id"`
	IsRecurring     bool               `json:"is_recurring"`
	ID              pgtype.UUID        `json:"id"`
}

func (q *Queries) UpdateTransaction(ctx context.Context, arg UpdateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, updateTransaction,
		arg.CategoryID,
		arg.Amount,
		arg.Merchant,
		arg.Note,
		arg.TransactionDate,
		arg.MessageID,
		arg.IsRecurring,
		arg.ID,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CategoryID,
		&i.Amount,
		&i.Merchant,
		&i.Note,
		&i.TransactionDate,
		&i.MessageID,
		&i.IsRecurring,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
