// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const softDeleteUser = `-- name: SoftDeleteUser :execrows
update public.users
set deleted_at = now()
where id = $1
  and deleted_at is null
`

func (q *Queries) SoftDeleteUser(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteUser, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateUserProfile = `-- name: UpdateUserProfile :one
update public.users
set name = $1,
    picture = $2
where id = $3
  and deleted_at is null
returning id, google_id, email, name, picture,
    created_at, updated_at, deleted_at
`

type UpdateUserProfileParams struct {
	Name    string      `json:"name"`
	Picture *string     `json:"picture"`
	ID      pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserProfile, arg.Name, arg.Picture, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GoogleID,
		&i.Email,
		&i.Name,
		&i.Picture,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
