package services

import (
	"context"
	"errors"
	"fmt"
	"time"

	"walletx-be/internal/domain/dto"
	"walletx-be/internal/ports"
	"walletx-be/pkg/models"
	"walletx-be/pkg/repository"

	"github.com/google/uuid"
)

type CreateRecurringInput = dto.CreateRecurringInput
type UpdateRecurringInput = dto.UpdateRecurringInput

var validFrequencies = map[string]bool{"weekly": true, "monthly": true, "yearly": true}

type RecurringService interface {
	CreateRecurring(ctx context.Context, userID uuid.UUID, input CreateRecurringInput) (*models.RecurringConfig, error)
	ListRecurrings(ctx context.Context, userID uuid.UUID) ([]models.RecurringConfig, error)
	GetRecurringByID(ctx context.Context, id, userID uuid.UUID) (*models.RecurringConfig, error)
	UpdateRecurring(ctx context.Context, id, userID uuid.UUID, input UpdateRecurringInput) (*models.RecurringConfig, error)
	DeleteRecurring(ctx context.Context, id, userID uuid.UUID) error
	ProcessDueRecurrings(ctx context.Context) error
}

type recurringService struct {
	recurringRepo    repository.RecurringRepository
	transactionRepo  repository.TransactionRepository
	cacheManager     ports.DashboardCacheManager
	logger           ports.Logger
}

func NewRecurringService(recurringRepo repository.RecurringRepository, transactionRepo repository.TransactionRepository, cacheManager ports.DashboardCacheManager, logger ports.Logger) RecurringService {
	return &recurringService{
		recurringRepo:   recurringRepo,
		transactionRepo: transactionRepo,
		cacheManager:    cacheManager,
		logger:          logger,
	}
}

func (s *recurringService) CreateRecurring(ctx context.Context, userID uuid.UUID, input CreateRecurringInput) (*models.RecurringConfig, error) {
	if !validFrequencies[input.Frequency] {
		return nil, fmt.Errorf("invalid frequency '%s': must be 'weekly', 'monthly', or 'yearly'", input.Frequency)
	}
	if input.Amount <= 0 {
		return nil, errors.New("amount must be greater than 0")
	}

	config := &models.RecurringConfig{
		UserID:      userID,
		CategoryID:  input.CategoryID,
		Amount:      input.Amount,
		Frequency:   input.Frequency,
		StartDate:   input.StartDate,
		NextDueDate: input.StartDate,
	}

	if err := s.recurringRepo.Create(ctx, config); err != nil {
		return nil, err
	}
	return config, nil
}

func (s *recurringService) ListRecurrings(ctx context.Context, userID uuid.UUID) ([]models.RecurringConfig, error) {
	return s.recurringRepo.List(ctx, userID)
}

func (s *recurringService) GetRecurringByID(ctx context.Context, id, userID uuid.UUID) (*models.RecurringConfig, error) {
	return s.recurringRepo.GetByID(ctx, id, userID)
}

func (s *recurringService) UpdateRecurring(ctx context.Context, id, userID uuid.UUID, input UpdateRecurringInput) (*models.RecurringConfig, error) {
	if !validFrequencies[input.Frequency] {
		return nil, fmt.Errorf("invalid frequency '%s': must be 'weekly', 'monthly', or 'yearly'", input.Frequency)
	}
	if input.Amount <= 0 {
		return nil, errors.New("amount must be greater than 0")
	}

	config, err := s.recurringRepo.GetByID(ctx, id, userID)
	if err != nil {
		return nil, err
	}

	config.Amount = input.Amount
	config.Frequency = input.Frequency
	if !input.StartDate.IsZero() {
		config.StartDate = input.StartDate
	}

	if err := s.recurringRepo.Update(ctx, config); err != nil {
		return nil, err
	}
	return config, nil
}

func (s *recurringService) DeleteRecurring(ctx context.Context, id, userID uuid.UUID) error {
	return s.recurringRepo.Delete(ctx, id, userID)
}

func (s *recurringService) ProcessDueRecurrings(ctx context.Context) error {
	configs, err := s.recurringRepo.GetDueConfigs(ctx)
	if err != nil {
		return err
	}

	if len(configs) == 0 {
		return nil
	}

	affectedUsers := make(map[uuid.UUID]bool)

	for _, config := range configs {
		catID := config.CategoryID
		transaction := &models.Transaction{
			UserID:          config.UserID,
			CategoryID:      &catID,
			Amount:          config.Amount,
			Merchant:        "Recurring Transaction",
			Note:            "Auto-generated by recurring schedule",
			TransactionDate: config.NextDueDate,
			MessageID:       nil,
			IsRecurring:     true,
		}

		if err := s.transactionRepo.Create(ctx, transaction); err != nil {
			continue
		}

		affectedUsers[config.UserID] = true

		config.NextDueDate = s.advanceDate(config.NextDueDate, config.Frequency)
		_ = s.recurringRepo.Update(ctx, &config)
	}

	for userID := range affectedUsers {
		s.invalidateDashboardCache(ctx, userID)
	}

	return nil
}

func (s *recurringService) invalidateDashboardCache(ctx context.Context, userID uuid.UUID) {
	if err := s.cacheManager.InvalidateUserCache(ctx, userID.String()); err != nil {
		s.logger.WithError(err).Warn("Failed to invalidate dashboard cache")
	}
}

func (s *recurringService) advanceDate(t time.Time, frequency string) time.Time {
	switch frequency {
	case "weekly":
		return t.AddDate(0, 0, 7)
	case "yearly":
		return t.AddDate(1, 0, 0)
	default:
		return t.AddDate(0, 1, 0)
	}
}
