package services

import (
	"context"
	"errors"
	"fmt"
	"time"

	"walletx-be/pkg/models"
	"walletx-be/pkg/repository"

	"github.com/google/uuid"
)

var validFrequencies = map[string]bool{"weekly": true, "monthly": true, "yearly": true}

// RecurringService defines the business logic contract for recurring transaction configs
type RecurringService interface {
	CreateRecurring(userID uuid.UUID, input CreateRecurringInput) (*models.RecurringConfig, error)
	ListRecurrings(userID uuid.UUID) ([]models.RecurringConfig, error)
	GetRecurringByID(id, userID uuid.UUID) (*models.RecurringConfig, error)
	UpdateRecurring(id, userID uuid.UUID, input UpdateRecurringInput) (*models.RecurringConfig, error)
	DeleteRecurring(id, userID uuid.UUID) error
	ProcessDueRecurrings() error
}

// CreateRecurringInput is the DTO for creating a recurring config
type CreateRecurringInput struct {
	CategoryID uuid.UUID `json:"category_id" binding:"required"`
	Amount     float64   `json:"amount"      binding:"required,gt=0"`
	Frequency  string    `json:"frequency"   binding:"required"`
	StartDate  time.Time `json:"start_date"  binding:"required"`
}

// UpdateRecurringInput is the DTO for updating a recurring config
type UpdateRecurringInput struct {
	Amount    float64   `json:"amount"    binding:"required,gt=0"`
	Frequency string    `json:"frequency" binding:"required"`
	StartDate time.Time `json:"start_date"`
}

type recurringService struct {
	recurringRepo   repository.RecurringRepository
	transactionRepo repository.TransactionRepository
	cacheRepo       repository.CacheRepository
}

func NewRecurringService(recurringRepo repository.RecurringRepository, transactionRepo repository.TransactionRepository, cacheRepo repository.CacheRepository) RecurringService {
	return &recurringService{
		recurringRepo:   recurringRepo,
		transactionRepo: transactionRepo,
		cacheRepo:       cacheRepo,
	}
}

func (s *recurringService) CreateRecurring(userID uuid.UUID, input CreateRecurringInput) (*models.RecurringConfig, error) {
	if !validFrequencies[input.Frequency] {
		return nil, fmt.Errorf("invalid frequency '%s': must be 'weekly', 'monthly', or 'yearly'", input.Frequency)
	}
	if input.Amount <= 0 {
		return nil, errors.New("amount must be greater than 0")
	}

	config := &models.RecurringConfig{
		UserID:      userID,
		CategoryID:  input.CategoryID,
		Amount:      input.Amount,
		Frequency:   input.Frequency,
		StartDate:   input.StartDate,
		NextDueDate: input.StartDate, // First due date equals start date
	}

	if err := s.recurringRepo.Create(config); err != nil {
		return nil, err
	}
	return config, nil
}

func (s *recurringService) ListRecurrings(userID uuid.UUID) ([]models.RecurringConfig, error) {
	return s.recurringRepo.List(userID)
}

func (s *recurringService) GetRecurringByID(id, userID uuid.UUID) (*models.RecurringConfig, error) {
	return s.recurringRepo.GetByID(id, userID)
}

func (s *recurringService) UpdateRecurring(id, userID uuid.UUID, input UpdateRecurringInput) (*models.RecurringConfig, error) {
	if !validFrequencies[input.Frequency] {
		return nil, fmt.Errorf("invalid frequency '%s': must be 'weekly', 'monthly', or 'yearly'", input.Frequency)
	}
	if input.Amount <= 0 {
		return nil, errors.New("amount must be greater than 0")
	}

	config, err := s.recurringRepo.GetByID(id, userID)
	if err != nil {
		return nil, err
	}

	config.Amount = input.Amount
	config.Frequency = input.Frequency
	if !input.StartDate.IsZero() {
		config.StartDate = input.StartDate
	}

	if err := s.recurringRepo.Update(config); err != nil {
		return nil, err
	}
	return config, nil
}

func (s *recurringService) DeleteRecurring(id, userID uuid.UUID) error {
	return s.recurringRepo.Delete(id, userID)
}

func (s *recurringService) ProcessDueRecurrings() error {
	configs, err := s.recurringRepo.GetDueConfigs()
	if err != nil {
		return err
	}

	if len(configs) == 0 {
		return nil
	}

	// Track unique user IDs for cache invalidation
	affectedUsers := make(map[uuid.UUID]bool)

	for _, config := range configs {
		catID := config.CategoryID
		transaction := &models.Transaction{
			UserID:          config.UserID,
			CategoryID:      &catID,
			Amount:          config.Amount,
			Merchant:        "Recurring Transaction",
			Note:            "Auto-generated by recurring schedule",
			TransactionDate: config.NextDueDate,
			MessageID:       nil,
			IsRecurring:     true,
		}

		if err := s.transactionRepo.Create(transaction); err != nil {
			continue // keep processing other configs even if one fails
		}

		// Mark user as affected for cache invalidation
		affectedUsers[config.UserID] = true

		config.NextDueDate = s.advanceDate(config.NextDueDate, config.Frequency)
		_ = s.recurringRepo.Update(&config)
	}

	// Invalidate dashboard cache for all affected users
	ctx := context.Background()
	for userID := range affectedUsers {
		s.invalidateDashboardCache(ctx, userID)
	}

	return nil
}

// invalidateDashboardCache removes cached dashboard data for a user
func (s *recurringService) invalidateDashboardCache(ctx context.Context, userID uuid.UUID) {
	cacheKey := fmt.Sprintf("cache:dashboard:budget_summary:%s", userID.String())
	_ = s.cacheRepo.DeleteCache(ctx, cacheKey)

	for _, month := range []int{1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12} {
		for _, year := range []int{2024, 2025, 2026, 2027} {
			dailyKey := fmt.Sprintf("cache:dashboard:daily_total:%s:%d:%d", userID.String(), month, year)
			_ = s.cacheRepo.DeleteCache(ctx, dailyKey)
		}
	}
}

func (s *recurringService) advanceDate(t time.Time, frequency string) time.Time {
	switch frequency {
	case "weekly":
		return t.AddDate(0, 0, 7)
	case "yearly":
		return t.AddDate(1, 0, 0)
	default: // "monthly"
		return t.AddDate(0, 1, 0)
	}
}
